# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Dilan/Finalproject/Finalproject.cache/wt [current_project]
set_property parent.project_path C:/Users/Dilan/Finalproject/Finalproject.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib -sv {
  C:/Users/Dilan/Documents/Downloads/final/counter6bit.sv
  C:/Users/Dilan/Documents/Downloads/final/instruction_memory.sv
  C:/Users/Dilan/Documents/Downloads/final/controller.sv
  C:/Users/Dilan/Documents/Downloads/final/reg_file.sv
  C:/Users/Dilan/Documents/Downloads/final/data_memory.sv
  {C:/Users/Dilan/Documents/Downloads/final/mtp_Team DJ_alu.sv}
  C:/Users/Dilan/Documents/Downloads/final/signext15_32.sv
  C:/Users/Dilan/Finalproject/Finalproject.srcs/seg_display.sv
  {C:/Users/Dilan/Documents/Downloads/final/fp_Team DJ_processor.sv}
  C:/Users/Dilan/Finalproject/Finalproject.srcs/basys3_wrapper.sv
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/Dilan/Finalproject/Finalproject.srcs/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/Dilan/Finalproject/Finalproject.srcs/Basys3_Master.xdc]


synth_design -top basys3_wrapper -part xc7a35tcpg236-1


write_checkpoint -force -noxdef basys3_wrapper.dcp

catch { report_utilization -file basys3_wrapper_utilization_synth.rpt -pb basys3_wrapper_utilization_synth.pb }
